config = dict(
    detection_models=[
        dict(
            type='scaled_yolo',
            model='results/models/scaled_yolo_fold_0.pt',
            config='configs/yolo/data_fold_0.yaml',
            img_shape=1024),
        dict(
            type='scaled_yolo',
            model='results/models/scaled_yolo_fold_1.pt',
            config='configs/yolo/data_fold_1.yaml',
            img_shape=1024),
        dict(
            type='scaled_yolo',
            model='results/models/scaled_yolo_fold_2.pt',
            config='configs/yolo/data_fold_2.yaml',
            img_shape=1024),
        dict(
            type='scaled_yolo',
            model='results/models/scaled_yolo_fold_3.pt',
            config='configs/yolo/data_fold_3.yaml',
            img_shape=1024),
        dict(
            type='scaled_yolo',
            model='results/models/scaled_yolo_fold_4.pt',
            config='configs/yolo/data_fold_4.yaml',
            img_shape=1024)
    ],
    grouped=False,
    meta_file_path='data/processed/vinbigdataVOC2012/train.csv',
    test_meta_file_path='data/processed/vinbigdataVOC2012/test.csv',
    val_ids='data/processed/vinbigdataVOC2012/image_sets/val.txt',
    test_ids='data/processed/vinbigdataVOC2012/image_sets/test.txt',
    visualize=False)
